language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"
install: "pip install -r requirements.txt -r requirements-dev.txt"
before_script: python setup.py develop
script: mamba --enable-coverage
after_success: 'coverage report --include="mamba/*","spec/*"'
